#!/usr/bin/python3 -B

import os
import sys
from config import *
from graph import graph_command
from component import component_command

print('Database directory:', os.path.expanduser(GRDB_DIR))

while True:
	line = input(PROMPT)
	argv = line.split()

	if len(argv) == 0:
		continue

	if argv[0] == 'quit':
		sys.exit(0)

	if argv[0] == 'graph' or argv[0] == 'g':
		graph_command(argv)
		continue

	if argv[0] == 'component' or argv[0] == 'c':
		component_command(argv)
		continue
